- name: Variables
  hosts: localhost
  vars:
  - Experiance:
      devops: 7
      AWS: 3
      Linux: 4
  tasks:
  - name: printing variables
    ansible.builtin.debug:
      msg: Experience in devops {{Experiance.devops}} years, Experience in AWS {{Experiance.AWS}} years, Experience in Linux {{Experiance.Linux}} years