- name: creating user
  hosts: localhost
  tasks:
  - name: check the user is exist or not
    ansible.builtin.command: id chinna
    register: output
    ignore_errors: true

  - name: check the outpu status
    ansible.builtin.debug:
      msg: "output is {{output}}"

  - name: check the outpu status
    ansible.builtin.debug:
      msg: "{{output.rc}}"
  
  - name: create user
    become: yes
    ansible.builtin.user:
      name: chinna
    when: output.rc != 0