- name: directory
  hosts: localhost
  tasks:
  - name: directory is exist or not
    ansible.builtin.stat:
      path: /etc/ansible/kumara
    register: output

  - name: printing output
    ansible.builtin.debug:
      msg: output is "{{output}}"
  
  - name: directory status
    ansible.builtin.debug:
      msg: directory not exist
    when: output.stat.exists == False