- name: directory
  hosts: localhost
  tasks:
  - name: check directory exist or not
    ansible.builtin.stat:
      path: /etc/ansible/raja
    register: output

  - name: printing the output
    ansible.builtin.debug:
      msg: output is "{{output}}"
  
  - name: crating directoy
    ansible.builtin.file:
      path: /etc/ansible/raja
      state: directory
    when: output.stat.exists == False
    