- name: instaling packages
  hosts: web_hosts
  tasks:
  - name: install packages
    become: yes
    ansible.builtin.yum:
      name: "{{item}}""
      state: installed
    loop:
    - postfix
    - python
    - php