- name: instaling packages
  hosts: web_server
  tasks:
  - name: install packages
    become: yes
    ansible.builtin.yum:
      name: "{{item}}"
      state: installed
    loop:
    - postfix
    - python3
    - php