- name: loops
  hosts: web_server
  tasks:
  - name: installing packages
    become: yes
    ansible.builtin.yum:
      name: "{{item}}"
      state: "{{item.state}}"
    loop:
      - {name: 'nginx', state: 'absent'}
      - {name: 'python3', state: 'absent'}
      - {name: 'git', state: 'installed'}

