- name: installing nodejs
  hosts: localhost
  become: yes
  tasks:
  - name: rpm package
    ansible.builtin.command: "curl -sL https://rpm.nodesource.com/setup_lts.x | bash"

  - name: instaling nodejs
    ansible.builtin.yum:
      name: nodejs
      state: installed