- name: Catalouge component
  hosts: catalouge_server
  become: yes
  tasks:
  - name: nodejs rpm
    ansible.builtin.shell: curl -sL https://rpm.nodesource.com/setup_lts.x | bash
  
  - name: installing node js
    ansible.builtin.yum:
      name: nodejs
      state: installed

  - name: check roboshop user is exist or not
    ansible.builtin.command: id roboshop
    register: output
    ignore_errors: true

  - name: creating user
    ansible.builtin.user:
      name: roboshop
    when: output.rc == 1

  - name: check directory is exist or not
    ansible.builtin.stat:
      path: /app
    register: output1

  - name: creating directory
    ansible.builtin.file:
      path: /app
      state: directory
    when: output1.stat.exists == False

  - name: downloading artifact
    ansible.builtin.get_url:
      url: https://roboshop-builds.s3.amazonaws.com/catalogue.zip
      dest: /tmp
      

  - name: unarchive
    ansible.builtin.unarchive:
      source: /tmp/catalogue.zip
      dest: /app
      remote_src: yes
  
  - name: installing dependences
    ansible.builtin.command: npm install
    args:
      chdir: /app

  - name: Setup SystemD Catalogue Service
    ansible.builtin.copy:
      src: catalogue.service
      dest: /etc/systemd/system/catalogue.service
    
  - name: demon-reload
    ansible.builtin.systemd:
      demon_reload: true

  - name: start and enable catalouge
    ansible.builtin.service:
      name: catalogue
      state: started
      enabled: yes

  - name: creating mongo repo
    ansible.builtin.copy:
      src: mongo.repo
      dest: /etc/yum.repos.d/mongo.repo
  
  - name: installing mongodb org shell
    ansible.builtin.yum:
      name: mongodb-org-shell
      state: installed

  - name: loading scema to mongodb
    ansible.builtin.command: mongo --host 172.31.95.215 </app/schema/catalogue.js

  - name: restart catalouge
    ansible.builtin.service:
      name: catalogue
      state: restarted


  

  



