- name: installing nginx
  hosts: web_server
  become: yes
  tasks:
  - name: instaling inginx
    ansible.builtin.yum:
      name: nginx
      state: installed
  - name: start inginx
    ansible.builtin.service:
      name: nginx
      state: started
  - name: enabling nginx
    ansible.builtin.service:
    name: nginx
    enabled: yes
    