- name: installing nginx
  hosts: web_server
  become: yes
  tasks:
  - name: instaling inginx
    ansible.builtin.yum:
      name: nginx
      state: installed
  - name: start inginx
    ansible.biultin.service:
      name: nginx
      state: started
      