- name: variables
  hosts: local host
  vars_prompt:
  - name: username
    prompt: Enter user name is?
    private: flase
  
  - name: password
    prompt: Enter Password?
    private: true
  tasks:
  - name: printing variables from promt
    ansible.builtin.debug:
      msg: login as {{username}}