- name: web componant
  hosts: web_server
  become: yes
  tasks:
  - name: install nginx
    ansible.builtin.yum:
      name: nginx
      state: installed

  - name: start and enable nginx
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: yes

  - name: delete the default folder
    ansible.builtin.file:
      path: /usr/share/nginx/html
      state: absent

  - name: creating directory
    ansible.builtin.file:
      path: /usr/share/nginx/html
      state: directory

  - name: downloading package
    ansible.builtin.get_url:
      url: https://roboshop-builds.s3.amazonaws.com/web.zip
      dest: /temp

  - name: unzip files
    ansible.builtin.unarchive:
      src: /temp
      dest: /usr/share/nginx/html
      remote_src: yes

  - name: reverse proxy config
     ansible.builtin.copy:
      src: roboshop.conf
      dest: /etc/nginx/default.d
      remote_src: yes
    